name: Run Tests

on: [push]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./UsingDorianFeatures

    - name: Run tests
      run: |
        pytest
      working-directory: ./UsingDorianFeatures
